[package]
name = "pub"
edition = "2021"
version = "0.1.0"

[dependencies]
dotenv = "0.15.0"
env_logger = "0.11.5"
paho-mqtt = "0.12.5"
rand = "0.8.5"
serde = { version = "1.0.208", features = ["derive"] }
serde_json = "1.0.125"
